# Generated by Django 2.2.7 on 2020-04-13 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='title',
            field=models.TextField(default='Measure of Zone of Inhibation'),
        ),
    ]
